server:
  env:"debug"
  address:"127.0.0.1"
  port:8080
  gracefulShutdownPeriod:30
  rateLimits:
    - limitType:"server"
      burst:500
      qps:100
      cacheSize:1
    - limitType:"ip"
      burst:50
      qps:10
      cacheSize:2048
  jwtSecret:chitchatserver

db:
  port:5432
  host:"localhost"
  name:"chitchat"
  user:"root"
  password:"Aa_123456"
  migrate:true