basePath: /
definitions:
  common.Response:
    properties:
      code:
        type: integer
      data: {}
      msg:
        type: string
    type: object
  model.AuthInfo:
    properties:
      authId:
        type: string
      authType:
        type: string
      createdAt:
        type: string
      id:
        type: integer
      updatedAt:
        type: string
      url:
        type: string
      userId:
        type: integer
    type: object
  model.AuthUser:
    properties:
      authCode:
        type: string
      authType:
        type: string
      name:
        type: string
      password:
        type: string
      setCookie:
        type: boolean
    type: object
  model.CreatedGroup:
    properties:
      creatorId:
        description: 创建者ID
        type: integer
      describe:
        description: 描述
        type: string
      name:
        type: string
    type: object
  model.CreatedUser:
    properties:
      avatar:
        type: string
      email:
        type: string
      name:
        type: string
      password:
        type: string
    type: object
  model.Group:
    properties:
      createdAt:
        type: string
      creatorId:
        description: 创作者Id
        type: integer
      describe:
        description: 描述
        type: string
      id:
        type: integer
      kind:
        description: 种类
        type: string
      name:
        type: string
      roles:
        description: 角色组集合
        items:
          $ref: '#/definitions/model.Role'
        type: array
      updatedAt:
        type: string
      updaterId:
        description: 更新 Id
        type: integer
      users:
        description: 用户集合
        items:
          $ref: '#/definitions/model.User'
        type: array
    type: object
  model.JWTToken:
    properties:
      describe:
        type: string
      token:
        type: string
    type: object
  model.Operation:
    enum:
    - '*'
    - edit
    - view
    type: string
    x-enum-comments:
      AllOperation: 所有操作
      EditOperation: 编辑操作
      ViewOperation: 查看操作
    x-enum-varnames:
    - AllOperation
    - EditOperation
    - ViewOperation
  model.Resource:
    properties:
      id:
        type: integer
      kind:
        type: string
      name:
        type: string
      scope:
        $ref: '#/definitions/model.Scope'
    type: object
  model.Role:
    properties:
      id:
        type: integer
      name:
        type: string
      namespace:
        description: 表示命名空间
        type: string
      rules:
        description: Rules 表示规则集合，是切片类型
        items:
          $ref: '#/definitions/model.Rule'
        type: array
      scope:
        allOf:
        - $ref: '#/definitions/model.Scope'
        description: Scope 表示范围，string类型
    type: object
  model.Rule:
    properties:
      operation:
        allOf:
        - $ref: '#/definitions/model.Operation'
        description: 操作
      resource:
        description: 资源
        type: string
    type: object
  model.Scope:
    enum:
    - cluster
    - namespace
    type: string
    x-enum-comments:
      ClusterScope: 串范围
      NamespaceScope: 命名空间范围
    x-enum-varnames:
    - ClusterScope
    - NamespaceScope
  model.UpdatedGroup:
    properties:
      describe:
        type: string
      name:
        type: string
      updaterId:
        type: integer
    type: object
  model.UpdatedUser:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
    type: object
  model.User:
    properties:
      authInfos:
        items:
          $ref: '#/definitions/model.AuthInfo'
        type: array
      avatar:
        type: string
      createdAt:
        type: string
      email:
        type: string
      groups:
        items:
          $ref: '#/definitions/model.Group'
        type: array
      id:
        type: integer
      name:
        type: string
      roles:
        items:
          $ref: '#/definitions/model.Role'
        type: array
      updatedAt:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    name: 作者：黄鹏举
    url: https://huangpengju.github.io/
  description: |-
    这是 chitchat 服务器 API 文档。
    查看应用版本：项目启动命令后追加-v=true
    指定应用配置路径：项目启动命令后追加-config=配置路径
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: ChitChat API
  version: "4.0"
paths:
  /api/v1/auth/token:
    post:
      consumes:
      - application/json
      description: user login | 用户登录
      parameters:
      - description: auth user info
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/model.AuthUser'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/common.Response'
            - properties:
                data:
                  $ref: '#/definitions/model.JWTToken'
              type: object
      summary: Login | 登录
      tags:
      - auth
  /api/v1/auth/user:
    post:
      consumes:
      - application/json
      description: Create user and storage
      parameters:
      - description: user info
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/model.CreatedUser'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/common.Response'
            - properties:
                data:
                  $ref: '#/definitions/model.User'
              type: object
      summary: Register user | 注册用户
      tags:
      - auth
  /api/v1/groups:
    get:
      description: List group | 查询所有group列表
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/common.Response'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/model.Group'
                  type: array
              type: object
      security:
      - JWT: []
      summary: List group | group 列表
      tags:
      - group
    post:
      consumes:
      - application/json
      description: Create group and stroage | 创建 group 和 stroage 存储
      parameters:
      - description: group info
        in: body
        name: group
        required: true
        schema:
          $ref: '#/definitions/model.CreatedGroup'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/common.Response'
            - properties:
                data:
                  $ref: '#/definitions/model.Group'
              type: object
      security:
      - JWT: []
      summary: Create group | 创建 group
      tags:
      - group
  /api/v1/groups/{id}:
    delete:
      description: Delete group | 删除指定的group
      parameters:
      - description: group id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/common.Response'
      security:
      - JWT: []
      summary: Delete group | 删除group
      tags:
      - group
    get:
      description: Get group | 通过id查询group
      parameters:
      - description: group id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/common.Response'
            - properties:
                data:
                  $ref: '#/definitions/model.Group'
              type: object
      security:
      - JWT: []
      summary: Get group | 获取 group
      tags:
      - group
    put:
      consumes:
      - application/json
      description: Update group and storage | 修改group和保存
      parameters:
      - description: group info
        in: body
        name: group
        required: true
        schema:
          $ref: '#/definitions/model.UpdatedGroup'
      - description: group id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/common.Response'
            - properties:
                data:
                  $ref: '#/definitions/model.Group'
              type: object
      security:
      - JWT: []
      summary: Update group | 修改 group
      tags:
      - group
  /api/v1/groups/{id}/users:
    delete:
      description: Delete user from group | 删除group中的user
      parameters:
      - description: group id
        in: path
        name: id
        required: true
        type: integer
      - description: user info
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/model.User'
      - description: user 的 name
        in: query
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/common.Response'
      security:
      - JWT: []
      summary: Delete user | 删除user
      tags:
      - group
    get:
      description: Get users | 根据 group 获取user集合
      parameters:
      - description: group id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/common.Response'
      security:
      - JWT: []
      summary: Get users | 获取user集合
      tags:
      - group
    post:
      description: Add user to group | 把user添加到group中
      parameters:
      - description: group id
        in: path
        name: id
        required: true
        type: integer
      - description: user info
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/model.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/common.Response'
      security:
      - JWT: []
      summary: Group Add user | 添加user
      tags:
      - group
  /api/v1/operations:
    get:
      description: List operations | 操作列表
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/common.Response'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/model.Operation'
                  type: array
              type: object
      security:
      - JWT: []
      summary: List operations | 操作列表
      tags:
      - rbac
  /api/v1/resources:
    get:
      description: List resources | 资源列表
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/common.Response'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/model.Resource'
                  type: array
              type: object
      security:
      - JWT: []
      summary: List resources | 资源列表
      tags:
      - rbac
  /api/v1/roles:
    get:
      description: List rbac role | rbac 角色列表
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/common.Response'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/model.Role'
                  type: array
              type: object
      security:
      - JWT: []
      summary: List rbac role | rbac 角色列表
      tags:
      - rbac
    post:
      consumes:
      - application/json
      description: Create rbac role | 创建 rbac 的角色
      parameters:
      - description: rbac role info
        in: body
        name: role
        required: true
        schema:
          $ref: '#/definitions/model.Role'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/common.Response'
      security:
      - JWT: []
      summary: Create rbac role | 创建 rbac 的角色
      tags:
      - rbac
  /api/v1/roles/{id}:
    delete:
      description: Delete role | 删除角色
      parameters:
      - description: role id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/common.Response'
      security:
      - JWT: []
      summary: Delete role | 删除角色
      tags:
      - rbac
    get:
      description: Get role | 获取一个 rbac 的角色
      parameters:
      - description: role id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/common.Response'
            - properties:
                data:
                  $ref: '#/definitions/model.Role'
              type: object
      security:
      - JWT: []
      summary: Get role | 获取一个 rbac 的角色
      tags:
      - rbac
    put:
      consumes:
      - application/json
      description: Update rbac role | rbac 修改角色
      parameters:
      - description: rbac role info
        in: body
        name: role
        required: true
        schema:
          $ref: '#/definitions/model.Role'
      - description: role id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/common.Response'
            - properties:
                data:
                  $ref: '#/definitions/model.Role'
              type: object
      security:
      - JWT: []
      summary: Update rbac role | rbac 修改角色
      tags:
      - rbac
  /api/v1/users:
    get:
      description: 获取用户列表并存储
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/common.Response'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/model.User'
                  type: array
              type: object
      security:
      - JWT: []
      summary: List user | 用户列表
      tags:
      - user
    post:
      consumes:
      - application/json
      description: 创建用户并存储
      parameters:
      - description: user 信息
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/model.CreatedUser'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/common.Response'
            - properties:
                data:
                  $ref: '#/definitions/model.User'
              type: object
      security:
      - JWT: []
      summary: Create user | 创建用户
      tags:
      - user
  /api/v1/users/{id}:
    get:
      description: 获取用户并保存
      parameters:
      - description: user id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/common.Response'
            - properties:
                data:
                  $ref: '#/definitions/model.User'
              type: object
      security:
      - JWT: []
      summary: Get user | 获取单个用户
      tags:
      - user
    put:
      consumes:
      - application/json
      description: 修改用户信息并保存
      parameters:
      - description: user info
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/model.UpdatedUser'
      - description: user id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/common.Response'
            - properties:
                data:
                  $ref: '#/definitions/model.User'
              type: object
      security:
      - JWT: []
      summary: Update user | 修改用户信息
      tags:
      - user
  /index:
    get:
      description: 返回后端主页 html 源代码
      produces:
      - text/html
      responses: {}
      summary: Home
      tags:
      - home
schemes:
- http
- https
securityDefinitions:
  JWT:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
